[package]
name = "php-5x-sys"
version = "0.1.0"
authors = ["Paweł Chojnacki <pawel.chcki@gmail.com>"]
edition = "2018"

[dependencies]
const_format = "0.2"

[build-dependencies]
php-build = { path = "../sys-build"}
rayon = "1.5"